---
name: hello
label: $( variable "label")
description: $( variable "description" )
icon_image: $( icon )

metadata_version: "2.7.0"
minimum_version_for_upgrade: 0.1.0
product_version: $( version )
provides_product_versions:
  - name: hello
    version: $( version )

rank: 90
serial: false

releases:
  - $( release "bpm" )

stemcell_criteria: $( stemcell )

runtime_configs: []

property_blueprints:
  - $( property "port" )

form_types: []
